### ISSUE TITLE
Не завершать поток заполнения данных до конца программы

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/nextgis_datastore#1]
До сих пор было сделано так, чтобы поток завершался и запускался снова при запросе новой порции данных (если успевал прошлый запрос отработать).

Это делалось для экономии памяти - но не получается. Таким образом поток надо завершать только если идет выход из программы или вызов onlowmemory.

В потоке нужно сдалеть sleep где-то на 20-50 мс, а остальное - проверка на новую порцию данных - уже реализована. Или, как вариант без sleep -- пробуждение потока по условию.

**Comment by NikitaFeodonit** [comment]
Также обратить внимание на этот [комментарий](https://github.com/nextgis/nextgis_datastore/commit/3ed141f473a30032dc78d502e639fa030c42bb5a#commitcomment-19707440) и на [этот](https://github.com/nextgis/nextgis_datastore/commit/3ed141f473a30032dc78d502e639fa030c42bb5a#commitcomment-19707441).

**Comment by NikitaFeodonit** [comment]
Закрыл по ошибке

**Comment by BishopGIS** [comment]
Сделано через thread pool - он сам управляет временем жизни и количеством потоков
