### ISSUE TITLE
Line layer crashes application on the load

### ISSUE THREAD

**Issue by NikitaFeodonit** [nextgis/nextgis_datastore#7]
Application based on the nextgis_datastore crashes on load a shape file with the lines. It is true for desktop_gl_viewer and android_nextgis_mobile.

Crash is here:
https://github.com/nextgis/nextgis_datastore/blob/master/src/ds/storefeaturedataset.cpp#L61
On the 4th iteration.

For more info see:
https://github.com/nextgis/android_nextgis_mobile/issues/16

**Comment by BishopGIS** [comment]
@NikitaFeodonit Еще актуально?

**Comment by NikitaFeodonit** [comment]
The application does not crash. But the layer "railway-line.shp" must be converted into the 3857 coordinate system. Then everything is drawn correctly.
