### ISSUE TITLE
#include "cpl_json.h" not found

### ISSUE THREAD

**Issue by Lecrapouille** [nextgis/nextgis_datastore#9]
got this error with Debian 9.3 while libgdal-dev was installed. cpl_json.h is not installed. Which library shall I have to install (found nothing on google) ? Thx

**Comment by BishopGIS** [comment]
**NextGIS datastore** library was tested only with modified ``GDAL`` version: https://github.com/nextgis-borsch/lib_gdal/tree/v2.3.4 (https://github.com/nextgis-borsch/lib_gdal/blob/v2.3.4/core/port/cpl_json.h)

Modifications are partially ported into the GDAL trunk: https://github.com/OSGeo/gdal/blob/trunk/gdal/port/cpl_json.h 
But build with GDAL trunk is not guaranteed. If you try with GDAL trunk don't forget remove strict version check here: https://github.com/nextgis/nextgis_datastore/blob/master/cmake/extlib.cmake#L121 ``VERSION 2.3.4 EXACT``

I wonder why this check not triggered on your current build.

**Comment by Lecrapouille** [comment]
@BishopGIS thanks for your fast answer I’ll give a try ! Yes cmake succeeded while this file seems not be present in my file system.

**Comment by BishopGIS** [comment]
No feedback in 25 days.
